version: "3.8"

services:
  thing:
    image: ghcr.io/gldecurtins/thing:main
    networks:
      - public
    ports:
      - "2001:8000"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.routers.thing.rule=Host(`thing.uemd.net`)"
        - "traefik.http.routers.thing.entrypoints=web"
        - "traefik.http.services.thing.loadbalancer.server.port=2001"
        - "traefik.http.routers.thing.service=thing"

networks:
  public:
    external: true
