version: "3.9"

services:
  stack:
    image: ghcr.io/gldecurtins/stack:main
    networks:
      - traefik
    ports:
      - "2001:2001"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.routers.stack.rule=Host(`stack.uemd.net`)"
        - "traefik.http.routers.stack.entrypoints=websecure"
        - "traefik.http.routers.stack.service=stack"
        - "traefik.http.services.stack.loadbalancer.server.port=2001"


networks:
  traefik:
    external: true
