version: "3.8"

services:
  thing-dev:
    build: container
    command: "uvicorn main:app --host 0.0.0.0 --reload --log-level debug"
    volumes:
      - ./container/app:/app
    ports:
      - "8000:8000"