version: "3.9"

services:
  thing:
    image: ghcr.io/gldecurtins/thing:main
    networks:
      - traefik
    ports:
      - "2001:2001"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.routers.thing.rule=Host(`thing.uemd.net`)"
        - "traefik.http.routers.thing.entrypoints=websecure"
        - "traefik.http.services.thing.loadbalancer.server.port=2001"
        - "traefik.http.routers.thing.service=thing"

networks:
  traefik:
    external: true
