version: "3.9"

services:
  thing-dev:
    build: container
    environment:
      - UVICORN_RELOAD=true
      - UVICORN_LOG_LEVEL=debug
    volumes:
      - ./container/app:/app
    ports:
      - "2001:2001"