version: "3.8"

services:
  thing:
    image: gldecurtins/thing:latest
    networks:
      - public
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.routers.thing.rule=Host(`thing.uemd.net`)"
        - "traefik.http.routers.thing.entrypoints=web"
        - "traefik.http.services.thing.loadbalancer.server.port=8080"
        - "traefik.http.routers.thing.service=thing"

networks:
  public:
    external: true
