version: "3.8"

name: thing
services:
  thing:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: "8080"
      protocol: tcp
    volumes:
    - type: bind
      source: ./app
      target: /app
networks:
  default:
    name: thing_default